### ISSUE TITLE
Consider moving this package to OTel-Go-Contrib

### ISSUE THREAD

**Issue by jmacd** [marwan-at-work/otel-exporter-datadog#3]
This is a nice library for the contrib repository:
https://github.com/open-telemetry/opentelemetry-go-contrib

**Comment by marwan-at-work** [comment]
@jmacd I'd be happy to move it there, I have a couple of questions: 

1. How should the directory structure be? For example: `<repo>/exporters/datadog`? 
2. Should each exporter be its own sub-module (has its own go.mod file), or its own repository? 
3. I imagine `github.com/open-telemetry/opentelemetry-go-contrib/datadog-exporter` is pretty long for a module name, anyway we can make it shorter like using the vanity server that already exists for OT? Something like `contrib.opentelemetry.io/go` ?

**Comment by jmacd** [comment]
I've already committed a `exporters/metric/dogstatsd`, which Chris is evaluating. You might add `exporters/metric/datadog`, I suggest.
